#!/usr/bin/env ruby

# mute any warnings
STDERR.reopen '/dev/null'

# FIXME: this script is way too slow - should do something faster

require '/var/hda/platform/html/config/boot'
require 'environment'

def main
	Share.push_shares
end

main
