#!/bin/bash

# gem install
dir=`mktemp -d`
cd $dir
wget http://rubyforge.org/frs/download.php/11289/rubygems-0.9.0.tgz
tar -xzf rubygems-0.9.0.tgz
cd rubygems-0.9.0
# wget
# http://rubyforge.org/frs/download.php/17190/rubygems-0.9.2.tgz
# tar -xzf rubygems-0.9.2.tgz
# cd rubygems-0.9.2
ruby setup.rb
gem install rails -y --no-rdoc --no-ri
gem install rake -y --no-rdoc --no-ri
gem install fcgi -y --no-rdoc --no-ri
gem install gruff -y --no-rdoc --no-ri
gem install rmagick -y --no-rdoc --no-ri
gem install gd2 -y --no-rdoc --no-ri
cd ..
rm -rf $dir

