html 				var/hda/platform
hda-gems-install 		usr/bin
hda-diskmount			usr/bin
pdc/logon.bat			var/hda/domain-settings/netlogon
fonts/*                         usr/share/fonts/TrueType
webapps				usr/share/hda-platform
hda-usermap			usr/share/hda-platform

#Files to be created in the usr/bin directory
hda-refresh-shares              usr/bin
hda-update-webapps              usr/bin
hda-create-db-and-user		usr/bin
amahi-download			usr/bin
